### PR TITLE
download.py: no longer downloads the entire video, only necessary segment for Kinetics. 

### PR DESCRIPTION
**Pull request by jremmons**
`Crawler/Kinetics/download.py` downloads the entire video from youtube (which can be tens of minutes long) then uses ffmpeg to extract the short clip specified in the Kinetics dataset (the clips are ~10 seconds on average). I have changed the code so that it only downloads the necessary segment of video from youtube, saving A TON of time downloading video.

### CODE REVIEW

**Comment by jremmons** [comment]
> We need to consider how to add this in. I vote for including it as another flavor rather than deprecating the current approach.

Sounds good to me. Do whatever you think is best in this regard.

> Do you mind to explain to me why you use FFmpeg via subprocess?

The original code before applying my patch uses `ffmpeg` via `subprocess` actually. I only made it so `youtube-dl` will get the URL needed to directly download the video (rather than downloading the video) then pass the URL to `ffmpeg` which does the downloading/clipping. 

> Does FFmpeg download the video?

Yes, `ffmpeg` downloads the video. This requires that `ffmpeg` be compiled with libopenssl (need to pass `--enable-openssl` to the configure script if compiling from source), but this built in by default if you `apt-get install ffmpeg`. Also, the directions in `Crawler/Kinetics/README.md` have the user install `ffmpeg` via a `conda` environment which includes libopenssl support. 

> It would be great to know how much is "A TON of time". Can you tell us the number of processes and cores of the machine(s) that you used?

So I did two things to speed up the download actually... (1) I made it so only the necessary component of the video was downloaded (via the `-ss` and `-t` flags to `ffmpeg`) and (2) I made it so the video is not re-encoded (the `-v:c libx264` flag in the original commandline for `ffmpeg` requires that the video be download, decoded, and re-encoded; I changed it so that is just copies the encoded video from youtube via the `-vcodec copy` flag [as a practical matter, ffmpeg will still re-encode a little bit of video at the beginning of the clip because the clip needs to start with a key-frame, but this should be cheap].)

I used `-n 96` on a 24 core machines (2x E5-2687W) to do the downloading, but I was network bound since I wasn't re-encoding the video (my CPU utilization was very low, like 4-6 cores at 100% max). I have a gigabit link to my machine and I was able to download at ~80-90MB/sec of video on average. 

When I downloaded the clipped train and validation videos, it took up 403GB of disk space on my machine. I gave up downloading using the original `download.py` after it had downloaded 1.2TB... I think the total size if I had downloaded all the videos would have been in the ballpark of ~8TBs, so a ~32x speedup if you are network bound like I was.

**Comment by escorciav** [comment]
Thanks for the detailed explanation. Very much appreciated.
I will discuss it with @cabaf

**Comment by lucasb-eyer** [comment]
I just tried this, but get a "No such file or directory" error for every single video from latest `ffmpeg`. This may or may not be related to #18 although the original `download.py` is still downloading correctly right now.

**Comment by jremmons** [comment]
@lucasb-eyer What version of ffmpeg and OS are you using? Can you you copy and paste the output of running `ffmpeg` with no arguments as well (I want to see what configuration was used when it was compiled). 

Also, are you sure that the issue is from ffmpeg? Or is it youtube-dl that is throwing the "No such file or directory" error.

**Comment by lucasb-eyer** [comment]
Hi, that is on Ubuntu 14.04 and I was using the latest-and-greatest ffmpeg binary/static distribution [from here](https://www.johnvansickle.com/ffmpeg/) (they are linked from the official ffmpeg site).

I'm sure it's from ffmpeg because I had to [remove the '-loglevel panic' flag](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L96) as well as [add a `print(err.output)` here](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L103) in order to see the error at all.

Actually, I just realized that I still have the scrollback buffer with the exact error, which is the following:

```
b"ffmpeg version N-45194-g40102a213-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers\n  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg\n  libavutil      56.  7.101 / 56.  7.101\n  libavcodec     58. 13.100 / 58. 13.100\n  libavformat    58. 10.100 / 58. 10.100\n  libavdevice    58.  2.100 / 58.  2.100\n  libavfilter     7. 12.100 /  7. 12.100\n  libswscale      5.  0.101 /  5.  0.101\n  libswresample   3.  0.101 /  3.  0.101\n  libpostproc    55.  0.100 / 55.  0.100\nb'https://r6---sn-4g5edn7s.googlevideo.com/videoplayback?expire=1520373609&mime=video%2Fmp4&key=yt6&fvip=6&itag=18&ipbits=0&lmt=1350822830440588&source=youtube&ratebypass=yes&dur=135.906&initcwndbps=3180000&pl=16&gir=yes&requiressl=yes&clen=9941100&id=o-ADxCjzPbGe3xCheBqMlb35mCaeV_W-MkrDlRd1NIwUab&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=CbueWoaVAeWg1wKLjblg&ip=134.130.139.113&mt=1520351863&mv=m&signature=013B0D21FFC2F19B608B0D80AE134ABCB0C1FF5F.E4418D82A5838DB587437FDB26D70BDE47D5D6D4&ms=au%2Crdu&c=WEB&mm=31%2C29&mn=sn-4g5edn7s%2Csn-4g5e6nl7': No such file or directory\n"
```

Actually, I see the problem now that I copy-pasted it in here and it's not as horribly formatted as in my tmux... The return value from the `subprocess.check_output` call to `youtube-dl` is a byte-string and gets formatted as b'...' when formatted using `'%s'`. So it's a python thing; I'm using Python 3.x. You can probably fix it by changing the one line to:

```
           direct_download_url = direct_download_url.strip().decode('utf-8')
```

but I don't want to stop the currently running process to try it myself :smile:

**Comment by jremmons** [comment]
@lucasb-eyer good catch. I'll update the pull request :).

**Comment by lucasb-eyer** [comment]
Note that I intentionally used `.decode` in my message instead of `str(..., encoding='utf-8')` because `.decode` works with both Python 2 and 3, whereas your change now won't work with Python2. (I didn't try the script in py2, so if it doesn't work with py2 anyways for other reasons, feel free to ignore this comment.)

**Comment by jremmons** [comment]
Oh gotcha. Wasn't aware of that. I'll change that.

**Comment by jremmons** [comment]
@escorciav I'll try to take a look at this tomorrow.

**Comment by escorciav** [comment]
No worries. Unfortunately, I deleted all the videos, but AFAIR it happened with any video where the start is significantly greater than zero.

Kinetics-400
`2pTztDoFiMc` is an example of a video where t_start is greater than zero.

Kinetics-600
`YEgqBGmmPV8` is an example of a video where t_start is greater than zero.

**Comment by jremmons** [comment]
@escorciav I just pushed a couple of changes that should resolve the bug you encountered.

The code will still only download the short video segments rather than the full videos, but it now re-encodes the segments so there shouldn't be any blank frames at the beginning of the videos. This will raise the CPU utilization significantly; to minimize the CPU usage I added the `-preset ultrafast` args to the `x264` encoder. This will increase the amount of space on disk the dataset will take up, but it shouldn't be more than 2x. (I will report back later once I finish downloading the dataset again with how large it is)

I'm currently downloading the training set at ~33MB/sec on the same machine I listed the specs for earlier. **I am now compute bound** rather than network bound. 

This updated version of `download.py` should still provide  a ~5-10x improvement in the download time.

**Comment by sarsees** [comment]
Ten thousand thumbs up to this pull request! Worked without a hitch for me.

**Comment by Arseny-N** [comment]
On Ubuntu 16.04 it failed with the following message,

    [aac @ 0x1bd8d80] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.

 adding `-strict -2` indeed helped.

**Comment by jremmons** [comment]
@Arseny-N

**Comment by wangtz** [comment]
Looking forward to this PR! I see that this PR is still open. Wondering what's the blocking issue preventing it from being merged? Thanks,

**Comment by escorciav** [comment]
@wangtz , thanks for your interest. Honestly, I missed out the last change from John. I'm truly sorry for that.

Please let me know if you wanna help us out.
- [ ] Create a docker image with the conda environment (similar to [this](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/environment.yml)) with the dependencies required for this patch. You can start with that environment, but it might be a good idea to ping John to verify this.
- [ ] Test John code in 50-100 videos. Use videos where `t_start` is greater than zero.
- [ ] Watch 5-10 videos to make sure that there are no artifacts.
- [ ] Push the docker image to Docker Hub.

- I may have some time after Feb 26 to test it out at small scale (50-100 videos).

**Comment by ninesunqian** [comment]
Hi all,
I have tested "-vcodec copy" may not get the accurate time. 
the command line is:
youtube-dl -g "https://www.youtube.com/watch?v=-wNyEUrxzFU"
ffmpeg -i '$the_output'  -ss 10 -to 20 -vcodec copy  1.mp4  #Duration: 00:00:09.37
ffmpeg -i '$the_output'  -ss 10 -to 20 -vcodec libx264  2.mp4   #Duration: 00:00:10.00
see: https://superuser.com/questions/1129396/ffmpeg-ss-t-seeking-output-is-not-accurate-any-workarounds

**Comment by Iamanorange** [comment]
You are right.
The inaccurate frame number/video duration is because that a predicted frame requires a reference frame which is intra encoded. But the frame specified by `-ss` may not be an I frame. 

You can't have your cake, and eat it too!

QQ截图20190331022527

Using original encoding `-vcodec copy` gives small file size and uncompressed frames.
Using secondary encoding `-vcodec libx264/libx265/libvpx-vp9` gives small file size and accurate frame numbers.
Using lossless secondary encoding `-vcodec xxx -lossless` gives uncompressed frames and accurate frame numbers.

**Comment by escorciav** [comment]
Interesting, @jremmons what is your take on the previous comment?

I was prone to believe that the reason was that [FFmpeg inside joblib is not threadsafe](https://github.com/escorciav/video-utils/issues/2). Now, we have another explanation.

It has always been a mystery for me why I couldn't make your PR download clean videos. It was quite fast though. Could you pls share your thoughts?

**Pull request closed without merging**
